config/routes.rb
Rails.application.routes.draw do
  # get 'pages/home'
  get 'about', to: "pages#about"
  get 'download_csv', to: "pages#download_csv"
  resources :articles, only: [ :index, :show, :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        if @article.save
            flash[:notice] = "successfully created"
            redirect_to @article
        else
            render 'new'
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def download_csv
    data = generate_csv_data

    respond_to do |format|
      format.csv do
        send_data data,
                  type: 'text/csv; charset=utf-8; header=present',
                  disposition: 'attachment; filename=example.csv'
      end
    end
  end

  private

  def generate_csv_data
    # Implement your logic to generate CSV data here
    CSV.generate { |csv| csv << ['Header 1', 'Header 2'] }
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/index.html.erb
<h1>Article List</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title %></td>
                <td><%= article.description %></td>
                <td>Placeholder</td>
            </tr>
        <% end %>
        
    </tbody>    
</table>

app/views/articles/new.html.erb
<h1>Creating New Article</h1>
<%= form_with scope: :article, url: articles_path, data: { turbo: false }, local: true do |form| %>

    <% if @article.errors.any? %>
        <h2>The following errors are prevnted form articles saved</h2>
        <% @article.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
    <% end %>

   


    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
    </p>

    <%= form.submit "Create" %>
<% end %>

app/views/articles/show.html.erb
<h1>Show Article details</h1>

<p><Strong>Title: </Strong> <%= @article.title %> </p>
<p><strong>Description: </strong> <%= @article.description %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to About</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<h1>Welcome to Home page</h1>
<%= link_to "About", about_path %>

<%= link_to 'Download CSV', download_csv_path(format: :csv) %>